services:
  stats-server:
    build: stats-server
    image: stats-server-client
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db


  stats-db:
    image: postgres:16.1
    container_name: postgres-stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm-service
    image: ewm-service-client
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm

